export enum StatusTypes {
  "NEW" = "NEW",
  "ACTIVE" = "ACTIVE",
  "COMPLETED" = "COMPLETED",
  "CANCELLED" = "CANCELLED",
}

export enum TasksTypes {
  "DEFAULT" = "DEFAULT",
  "RECURRING" = "RECURRING",
  "SCHEDULED_RECURRING" = "SCHEDULED_RECURRING",
  "SCHEDULE" = "SCHEDULE",
}

export enum DATA_FETCHING_STATUS {
  "NODATA" = "NODATA",
  "FETCHING" = "FETCHING",
  "ERROR" = "ERROR",
  "LOADED" = "LOADED",
}
