name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"