name: On Pull Request
run-name: ${{ github.actor }} running on-pull-request
on: [opened, edited, reopened]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
      - run: npx lint-staged